### ISSUE TITLE
'class' field does not return expected result

### ISSUE THREAD

**Issue by bbck** [defeated/wow_community_api#11]
Since class is a reserved keyword it makes retrieving it for a character difficult.

``` ruby
character = WowCommunityApi::Character.find_by_realm_and_name("Kil'jaeden", "Thehermit")
character.name # Thehermit
character.realm # Kil'jaeden
character.class # OpenStruct
```

Using the old xml armory class_id as the key by default may prevent some headaches.

**Comment by defeated** [comment]
good catch! i'll look into aliasing the "class" JSON key returned by:

http://us.battle.net/api/wow/character/kiljaeden/thehermit

as something like `class_name`. (the new web API doesn't currently expose a `class_id` attribute)

**Comment by defeated** [comment]
the `class` key is now replaced by `class_id` as suggested. thanks for filing this!

eventually this may be deprecated in favor of a `character_class` attribute that will do the sub-query for us. the syntax would look something like:

``` ruby
character = Character.find_by_realm_and_name 'realm', 'name'
puts character.character_class.name # => Paladin
```

(I'm looking at ActiveModel and ActiveResource and am open to other suggestions! but where Blizzard's API is currently read-only, I'm not sure we need a framework that fully supports RESTful CRUD yet.)
