### ISSUE TITLE
Allow optional fields to be specified

### ISSUE THREAD

**Issue by incendium** [defeated/wow_community_api#4]
Not sure how you wanted to flesh out the API, so I am opening this feature request.

Samples:
- `Character.find_by_realm_and_name('uther', 'malkyth', :fields => ['stats', 'talents'])` would become http://us.battle.net/api/wow/character/uther/malkyth?fields=stats,talents
- `Guild.find_by_realm_and_name('uther', 'nova', :fields => ['members', 'achievements'])` would become http://us.battle.net/api/wow/guild/uther/nova?fields=members,achievements

While this is changing, it might be a good idea to add support for multiple realms on the Realm class as well.

**Comment by defeated** [comment]
agreed! this is on my todo list, i just hadn't figured out a good way to do nested structs.

for example, i would like to be able to do something like:

```
c = Character.find_by_realm_and_name('arygos', 'mordread', :guild)
puts c.name # => Mordread
puts c.guild.name # => Homestarmy
```

i'm still going through Blizzard's documentation at http://blizzard.github.com/api-wow-docs/ and learning what all is supported.

**Comment by incendium** [comment]
What's the reasoning behind using Structs instead of Hashes?

**Comment by defeated** [comment]
if we used hashes, the consumer code would look something like this instead:

```
results = Character.find_by_realm_and_name('arygos', 'mordread', :guild)
puts results['character']['name']
puts results['character']['guild']['name']
```

and that certainly works, but it's noisy.

part of Ruby's standard library is an ["open struct"](http://ruby-doc.org/stdlib/libdoc/ostruct/rdoc/classes/OpenStruct.html) object that optionally takes a Hash as a constructor argument. It turns all keys in the Hash into properties on the struct.

the Struct behaves similarly to a class and provides a pretty clean migration path if we ever need to implement concrete entities like Character (and explicitly define its properties.)

For the optional fields, Blizzard returns a nested JSON object. That is already converted into nested Hashes by HTTParty, and I added support for converting nested Hashes into OpenStructs in commit [630a4d](https://github.com/defeated/wow_community_api/commit/630a4d), so look for the optional fields support possibly tonight.

**Comment by defeated** [comment]
per http://blizzard.github.com/api-wow-docs/#id3525212 we can now pass an optional 3rd parameter to the `find_by_realm_and_name()` method on `Guild` and `Character`. It should be a symbol (or array of symbols) matching the names of Blizzard's optional fields.

the following now works:

```
c = Character.find_by_realm_and_name('arygos', 'mordread', :guild, :titles)
puts c.name # => Mordread
puts c.guild.name # => Homestarmy
```

alternatively, if you have an array of symbols already built, you can use that as well:

```
c = Character.find_by_realm_and_name('arygos', 'mordread', [:guild, :titles])
```

(documentation is still forthcoming, that will be my next push once we're mostly feature complete.)

p.s. - none of this is set in stone - so I'm open to suggestions on how this API looks! (for example, I don't love `find_by_realm_and_name`. while it's pretty intention-revealing, it's a bit of a mouthful.)

on paper, something like `c = Character.on('arygos').named('mordread').with(:titles, :professions).find()` looks pretty sexy.

**Comment by incendium** [comment]
Coming from Java, I'm (unfortunately) used to verbosity, but that latter chain does indeed look pretty sexy. Great job on the enhancements!
